
var ErrorLog = {

    SUCCESS: 0,
    ERROR_USER_NOT_FOUND: 1,

    ERROR_FIELD_STATUS_NOT_EMPTY: 10,
    ERROR_FIELD_STATUS_NOT_GROWING: 11,
    ERROR_FIELD_STATUS_NOT_DONE: 12,

    ERROR_STORAGE_NOT_REDUCE: 20,
    ERROR_STORAGE_NOT_ADD: 21,

    ERROR_RUBY_NOT_REDUCE: 30,

};